config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] },
  numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ol>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
      <%= restaurant[:address] %>
    </li>
  <% end %>
</ol>

<%= link_to 'Add new restaurant', 'restaurants/new', class:'btn btn-primary' %>

app/views/restaurants/new.html.erb
<h1>Add New Restaurant</h1>
<div class="container">
  <%= simple_form_for [@restaurant] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.submit %>
  <% end %>
</div>
<br>
<div class="container">
  <%= link_to 'Home', restaurants_path, class:'btn btn-primary' %>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<h3>Reviews</h3>
<div class="container">
  <% if @restaurant.reviews.empty? %>
    <p>No Reviews</p>
  <% else %>
    <% @restaurant.reviews.each do |review| %>
      <p>
        <%= review.content %> - rating:
        <strong> <%= review.rating %> </strong>
      </p>
    <% end %>
  <% end %>
</div>

<h3>Details</h3>
<div class="container">
  <p>Cuisine: <%= @restaurant.category %></p>
  <p>Address: <%= @restaurant.address %></p>
  <p>Phone: <%= @restaurant.phone_number %></p>
</div>

<%= link_to 'Home', restaurants_path, class:'btn btn-primary' %>
<br>
<br>
<h2>Add New Review</h2>
<div class="container">
  <%= simple_form_for [@restaurant, Review.new] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit %>
  <% end %>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Add New Review</h1>
<div class="container">
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit %>
  <% end %>
</div>
<br>
<%= link_to 'Home', restaurants_path, class:'btn btn-primary' %>